version: '3.3'

services:
   db:
     image: hypriot/rpi-mysql:latest
     restart: always
     volumes:
       - ./data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_DATABASE
       - MYSQL_USER
       - MYSQL_PASSWORD
       - PUID
       - PGID
   wordpress:
     image: wordpress:5-fpm
     depends_on:
       - db
     restart: always
     volumes:
       - ./wordpress:/var/www/html
     environment:
       - WORDPRESS_DB_HOST
       - WORDPRESS_DB_USER
       - WORDPRESS_DB_PASSWORD
       - PUID
       - PGID
   letsencrypt:
     image: linuxserver/letsencrypt
     container_name: letsencrypt
     ports:
       - 443:443
       - 80:80
     volumes:
       - ./letsencrypt/config:/config
       - ./devportfolio:/var/www/html/devportfolio
       - ./wordpress:/var/www/html/wordpress
       - ./uploads.ini:/config/php/php-local.ini
       - ./cacert.pem:/config/php/cacert.pem
     restart: always
     depends_on:
       - wordpress
     environment:
       - VALIDATION
       - PUID
       - PGID
       - EMAIL
       - URL
       - SUBDOMAINS
       - TZ
   ddns:
     image: peteward44/godaddy-ddns:latest
     restart: always
     volumes:
       - ./godaddy-ddns:/etc/cron.d/godaddy-ddns
     environment:
       - GODADDY_KEY
       - GODADDY_SECRET
       - GODADDY_DOMAIN
       - GODADDY_TYPE
       - GODADDY_NAME

